name: TestWorkFlow

on: push

jobs:
    test_job:
        runs-on: ubuntu-latest

        steps:
        - name: Print message
          run: echo "hello!"
        - name: Step 2
          run: mkdir test
        - name: Step 3
          run: ls -a
