name: TestWorkFlow

on: push

jobs:
    test_job:
        runs-on: ubuntu-latest

        steps:
        - name: Print message
          run: |
           echo "hello!"
           mkdir test
           ls -a
